# taken from @zoldycktmbot
TRUTH = (
    "දිය යට බුබුලු සහ වැහි බිංදු එකිනෙකට ප්‍රතිවිරුද්ධ දෙයකි",
    "ඔබ මකන්නෙකු මිලට ගන්නේ නම් ඔබ වචනාර්ථයෙන් ඔබේ වැරදි සඳහා ගෙවනු ලැබේ.",
    "මිනිසුන් සඳ මත ජනපදකරණය කරයි, එය බොහෝ විට විශ්‍රාමික නිවාස ආකර්ෂණය කර ගනු ඇත, මන්ද දුර්වල ගුරුත්වාකර්ෂණය නිසා වැඩිහිටියන්ට ශක්තිමත් බවක් දැනෙනු ඇත.",
    "ඔබ වැඩිපුරම සැලකිලිමත් වන පුද්ගලයාට ඔබව වඩාත්ම විනාශ කිරීමේ හැකියාව ඇත.",
    "මාතෘකාව තුළ “ඒ සඳහා රැඳී සිටින්න” සහිත ඕනෑම වීඩියෝවක් ඉතා දිගු වේ.",
    "ඔබේ වයස අවුරුදු ගණන ඔබ සූර්යයා වටා කොපමණ වාරයක් රවුම් කර ඇත්ද, නමුත් මාස ගණනක් තුළ ඔබේ වයස වන්නේ සඳ ඔබව කොපමණ වාරයක් රවුම් කර ඇත්ද යන්නයි.",
    "ආහාර ගැනීමේදී ඔබේ දිව සපාකෑම දශක ගණනාවක අත්දැකීම් සහිතව වුවද ඔබට තවමත් ඉස්කුරුප්පු කළ හැකි ආකාරය පිළිබඳ කදිම නිදසුනකි.",
    "ඔබේ නිවස බල ගැන්වී ඇත්තේ සැතපුම් මිලියන 93 ක් දුරින් පිහිටි රැහැන් රහිත න්‍යෂ්ටික විලයන ප්‍රතික්‍රියාකාරකයකිනි. ඔබේ වහලයේ සූර්ය පැනල ඇති බව පැවසීමට වඩා සිසිල් ය.",
    "වඩාත්ම තැතිගන්වන හැඟීම නම් යමෙකු වීථියේදී ඔබට සිනාසෙන අතර ඔබ සිනාසීමට තරම් වේගයෙන් ප්‍රතික්‍රියා නොකරන විටය.",
    "ජීවත්ව සිටින විට දිරාපත්වීම වැළැක්වීම සඳහා දත් නිරන්තරයෙන් නඩත්තු කිරීම අවශ්‍ය වන නමුත් පොසිල ලෙස තැන්පත් කර වසර දහස් ගණනක් ජීවත් වීමට ඒවා සමත් වේ.",
    "ෆෝල්ඩරයක් යනු ඔබට නැවීමට අවශ්‍ය නැති දේවල් සඳහා ය.",
    "සමහර විට උදේ අවදි වීමෙන් ඔබ නැරඹීමෙන් ඉවත් වීමට තීරණය කළ ජරා චිත්‍රපටයක් නැවත ආරම්භ කිරීමක් මෙන් දැනේ.",
    "සෑම දෙයක්ම සුමටව සිදුවුවහොත්, ඔබට අද මතක නැත.",
    "සැබෑ ජීවිතයේ දී ඔබ නව පුද්ගලයින් මුණගැසෙන විට, ඔබේ සිහින ලෝකය සඳහා තවත් චරිත අගුළු හරිනු ඇත.",
    "සමහර විට ඔවුන් සන්ස්ක්‍රීන් “පිළිකා නාශක ක්‍රීම්” ලෙස නම් කළහොත් වැඩි පිරිසක් එය පැළඳ සිටී.",
    "මීට වසර 200 කට පෙර, මිනිසුන් නිහ ly ව වීදුරු මත තට්ටු කිරීමෙන් සන්නිවේදනය කරනු ඇතැයි මිනිසුන් කිසි විටෙකත් අනුමාන නොකරනු ඇත.",
    "දෙමව්පියන් තම පුතුන් බාගත කරන දේ ගැන කනස්සල්ලට පත්වන අතර තම දියණියන් උඩුගත කරන දේ ගැන කරදර වෙති.",
    "ඔබ යමෙකුගේ වයසට සමාන වන්නේ කෙසේද යන්න පිස්සුවකි, නමුත් ඔබේ ජීවිතයේ සම්පූර්ණයෙන්ම වෙනස් අවධියක.",
    "ඔයාට මැරෙන්න ඕනේ කියලා හිතනකොට, ඔයාට ඇත්තටම මැරෙන්න ඕන නෑ, ඔයාට මේ විදියට ජීවත් වෙන්න ඕන නෑ.",
    "තාක්ෂණික වශයෙන්, කිසිවෙකු මෙතෙක් හිස් කාමරයක නොසිටියේය.",
    "ළූණු යනු ආහාරයේ බාස් වාදකයයි. ඔබ එය තනිවම භුක්ති විඳින්නේ නැත, නමුත් එය එහි නොතිබුනේ නම් ඔබට එය මග හැරෙනු ඇත.",
    "අපි ඇවිදින්න කම්මැලි නිසා අපි කම්මැලි නිසා ඔවුන් ගමන් කිරීමට කම්මැලි නිසා වීඩියෝ ගේම්ස් හි සෑම තැනකම ධාවනය කරමු, නමුත් සැබෑ ජීවිතයේ අපි සෑම තැනකම ඇවිදිමින් සිටියෙමු.",
    "ඔබ විසින් සාදන ලද සෑම තීරණයක්ම මෙම වාක්යය කියවීමට ඔබව ගෙන ආවේය.",
    " නිහඬ වෙන්න  යන වචනය බොහෝ විට ඉතා හයියෙන් කියනු ලැබේ.",
    "සෑම කෙනෙකුම ඔබ වෙහෙස මහන්සි වී වැඩ කිරීමට කැමතියි, නමුත් ඔබ කොතරම් වෙහෙස මහන්සි වී වැඩ කරනවාද යන්න කිසිවෙකුට ඇසීමට අවශ්‍ය නැත.",
    "අපි සැරයටියක් මත හිසකෙස්වලින් දත් මදින්නෙමු.",
    "ඔබගේ අමුතු අවස්ථා කිසිවෙකුට මතක නැත, නමුත් ඔවුන් කාර්යබහුල වන්නේ ඔවුන්ගේම මතක තබා ගැනීමෙනි.",
    "ගොළු අය සරල අදහස් හැකිතාක් සංකීර්ණ ලෙස පැවසීමට උත්සාහ කරන අතර බුද්ධිමත් අය සංකීර්ණ අදහස් හැකිතාක් සරල ලෙස පැවසීමට උත්සාහ කරති.",
    "සමහර අය සිතන්නේ ඔවුන් ඔබට වඩා හොඳ බවයි. සමහර අය සිතන්නේ ඔවුන් දුප්පත් නිසා ඔවුන් ඔබට වඩා හොඳ බවයි.",
    "ලොකුම උත්ප්‍රාසය වන්නේ කාලය ඉතිරි කර ගැනීම සඳහා පරිගණක සහ ජංගම දුරකථන නිර්මාණය කිරීමයි!",
    "මී පැණි ප්‍රථම වරට සොයාගත් පසු, කෘමීන්ගෙන් ලබා ගත හැකි ඕනෑම රොන්මඩයක් මිනිසුන් රස පරීක්‍ෂා කරන කාලයක් තිබෙන්නට ඇත.",
    "ඔබ ඔවුන්ව කලකිරීමට පත් කරනවා වෙනුවට ඔබේ දෙමාපියන් ඔබව කලකිරීමට පත් කරන විට ඔබ වයසට යන බව ඔබ දන්නවා.",
    "මිනිසුන් නිර්මාණය කර ඇත්තේ අත්දැකීම් තුළින් ඉගෙනීම සඳහා වන අතර අධ්‍යාපන ක්‍රමය විසින් එය සකස් කර ඇති බැවින් අපට අත්දැකීම් නොලැබේ.",
    "දිලිසීම කෙරෙහි අවධානය යොමු කිරීමෙන්, ඔබ සෙමෙන් සෙමෙන් ඇසේ ... හුස්ම ගැනීමට සමාන වේ.",
    "රථවාහන තදබදයට ඉක්මන් වන රියදුරන් සාමාන්‍යයෙන් අනතුරු වළක්වා ගන්නේ ඔවුන් මග හැරීමට උත්සාහ කළ ගමනාගමනය නිර්මාණය කරමිනි.",
    "ප්‍රබන්ධයෙන් විවාහ වන චරිත වචනාර්ථයෙන් එකිනෙකා සඳහා නිර්මාණය කරන ලද්දකි.",
    "ළදරුවන් යනු ඕනෑම භාෂාවකින් වැඩසටහන්ගත කළ හැකි පිරිසිදු දෘඩ තැටියකි ",
    "මිනිසාට සෑම රෝගයක්ම සුව කරන ආශ්චර්යමත් ඖෂධයක්  තිබිය හැකිය, එය මීයන් මත ක්‍රියා නොකරන නිසා අපි කිසි විටෙකත් නොදැන සිටින්නෙමු.",
    "රයිනෝස් පරිණාමය වූයේ ආරක්ෂාව සඳහා අං වැඩීම සඳහා ය, නමුත් එය වඳ වී යාමට හේතුව එයයි.",
    "අවුරුදු 25-50ක් තුළ අප සියල්ලන්ම මිය යන නිසා සමහර විට අපට කාල සංචාරකයින් සොයා ගත නොහැක.",
    "නින්ද යනු මරණයේ අත්හදා බැලීමේ අනුවාදය වන අතර, එය ඔබගේ ක්‍රියාකාරකම් මත පදනම් වූ දැන්වීම් සමඟ පවා පැමිණේ.",
    "ස්පයි චිත්‍රපට පිළිබඳ වඩාත්ම යථාර්ථවාදී නොවන දෙය නම් වායු වාතාශ්‍රය පද්ධතිය කෙතරම් පිරිසිදුද යන්නයි!",
    "ක්‍රීඩා වලදී අපි දෘඩ ප්‍රකාර අගුළු ඇරීමට පහසු ක්‍රම හරහා ක්‍රීඩා කරමු. ජීවිතයේ දී අපි පහසු මාතයන් අගුළු ඇරීමට දෘඩ මාතයන් හරහා සෙල්ලම් කරමු.",
    "නිහඬ මිනිසුන් ඝෝෂාකාරී  මිනිසුන්ට වඩා දක්ෂ බව පෙනේ, මන්ද ඔවුන් ඔවුන්ගේ මෝඩ සිතුවිලි තමන්ටම තබා ගනී.",
    "ග්‍රීන්ලන්තය ඇත්ත වශයෙන්ම කොළ පැහැයට හැරේ නම්, අප සියල්ලන්ම ඉස්කුරුප්පු කර ඇත.",
    "ඔබේ සිහිනයේ යමෙක් දක්ෂ දේ පවසන්නේ නම්, එය ඇත්ත වශයෙන්ම ඔබේම දක්ෂතාවය පෙන්නුම් කරයි.",
    "ප්‍රසිද්ධ චිත්‍රපට උපුටා දැක්වීම් බැර වන්නේ නළුවාට මිස ඒවා ලියූ සැබෑ ලේඛකයාට නොවේ.",
    "බයිසිකලයක් පැදවිය යුතු ආකාරය කිසිවෙකු ඔබට උගන්වන්නේ නැත. ඔබ එය ක්‍රියාත්මක කරන තුරු ඔවුන් ඔබව උද්දීපනය කරයි.",
    "මොළය දෙවැන්න නොසලකා හැරියේ මන්දැයි ඔබගෙන්ම විමසන්න.",
    "ඔබගේ මුළු ජීවිතයෙන් 80% ක් පමණ ඔබට අමතක වී ඇති අතර ඔබට මතක ඇති බොහෝ මතකයන් ඇත්ත වශයෙන්ම සිදුවූ දෙයට වඩා නිවැරදි නොවේ.",
    "අනාගතයේදී වීඩියෝ ක්‍රීඩා වලදී ළමයින්ට තම දෙමාපියන්ට එරෙහිව ජයග්‍රහණය කිරීම බොහෝ අපහසු වනු ඇත.",
    "සෑම කෙනෙකුටම අඩුපාඩු තිබේ, ඔබ ඔබේ ඒවා හඳුනා නොගන්නේ නම්, ඔබට නව එකක් තිබේ.",
    "දරුවෙකු ඇති දැඩි කිරීම ඔබේ ආදේශනය පුහුණු කිරීමකි.",
    "ඕපන් ආරම්භ වන්නේ සංවෘත කවයකින් වන අතර, ක්ලෝස් ආරම්භ වන්නේ විවෘත කවයකින් ය.",
    "කිසිම හේතුවක් නොමැතිව ඔබට වෛර කළ, තවමත් එසේ කරන කෙනෙක් සිටී.",
    "පොප්කෝන් සොයාගැනීමෙන් පසු, අහඹු බීජ විශාල ප්‍රමාණයක් පුලුස්සා තිබිය යුතුය.",
    "හොඳ රාත්‍රී නින්දකට වඩා වැදගත් වන්නේ නින්දට යාමයි.",
    "නව මෝස්තර ශිල්පියෙකුට අවශ්‍ය කොණ්ඩා කැපීම නිවැරදිව විස්තර කළ හැකි අය භාග්‍යවන්තයෝ ය.",
    "බොහෝ අය තමන් උපයා නොගත් මුදල් වියදම් කරති, ඔවුන්ට අවශ්‍ය නැති දේවල් මිලට ගැනීමට, ඔවුන් අකමැති පුද්ගලයින් විශ්මයට පත් කිරීමට!",
    "තේමා උද්‍යාන සේවකයින් බිහිසුණු කෑගැසීම් සහ උද්දීපනය අතර වෙනස පැවසීමට හොඳ විය යුතුය.",
    "6 සිට 6:30 දක්වා පැය 5:50 සිට 6:20 දක්වා පැය භාගයක් වැඩියෙන් දැනේ",
    "ලොගවුට් වීමට පෙර අවසන් පිවිසුම් උත්සාහයේදී ඔබගේ මුරපදය නිවැරදිව ලබා ගැනීම අප බොහෝ දෙනා අත්විඳින අවසාන මොහොතේ බෝම්බයක් නිරායුධ කිරීමට ආසන්නතම දෙයයි.",
    "ඇඳට පෙර පොඩ්කාස්ට් වලට සවන් දීම යනු කතන්දර-කාලයේ වැඩිහිටි අනුවාදයයි.",
    "සියලුම අපරාධකරුවන් මංකොල්ලකෑම නැවැත්වුවහොත් ආරක්ෂක කර්මාන්තය වැටෙනු ඇති අතර ඔවුන්ට පහසුවෙන් මංකොල්ලකෑමට යා හැකිය.",
    "තල්මසුන් ටොන් එකක් ඇත්තෙන්ම තල්මසෙකු මෙන් ය.",
    "ඔබ වයසට ගිය විට, ඔබ පරණ ඔබ තාක්‍ෂණිකව නවක වන අතර ඔබේ තරුණ ආත්මය ඔබ මහලු ය.",
    "පැරෂුට් පිළිබඳ බොහෝ සෘණාත්මක සමාලෝචන ඔබට අන්තර්ජාලයේ සොයාගත නොහැක.",
    "මිනිසුන් එය අගය කිරීමට නොසිටින විට අපි ඔවුන්ට වඩාත්ම ආදරය හා අගය පෙන්වමු.",
    "අපි දහස් වාරයක් නිදා ගැනීමට පුරුදු වී සිටිමු, නමුත් එය හොඳින් කළ නොහැක.",
    "පෘථිවිය සුරැකීමට වඩා සතුරු පරිසරයක් සහිත වෙනත් ග්‍රහලෝකයකට යාමට මිනිසුන් වැඩි උනන්දුවක් දක්වයි - ඔවුන් පරිපූර්ණ ලෙස හැඩගස්වා ඇති ග්‍රහලෝකය.",
    "බොහෝ මිනිසුන්ගේ ජීවිතයේ ප්‍රීතිමත්ම අවස්ථාව වන්නේ ඔවුන්ගේ මොළය තවමත් පූර්ණ ලෙස වර්ධනය වී නොමැති අවස්ථාවයි.",
    "වඩාත් ඵලලදායී අනතුරු ඇඟවීමේ ඔරලෝසුව සම්පූර්ණ මුත්‍රාශයකි.",
    "ඔබ බොහෝ විට මිලියන ගණනක් දෙනා සමඟ සමමුහුර්ත කර ඇත.",
    "අපි මුලින්ම සතුන් මත ඖෂධ පරීක්‍ෂා කරන බැවින් මීයන්ගේ ඖෂධ මිනිස් ඖෂධයට වඩා වසර ගණනක් ඉදිරියෙන් සිටිය යුතුය.",
    "නිවාඩු දිනයට පෙර රාත්‍රිය සැබෑ නිවාඩු දිනයට වඩා තෘප්තිමත් ය.",
    "මැදිං ඇඩ් එකක් දාන්න එපැයි 😅 ඔන්න දැම්ම ඈෑ........\n😜Chat Group 👉 @GangOfMafiaTeam \n👨‍💻 @Mafia_Update  ",
    "කොහේ හරි, හොඳම මිතුරන් දෙදෙනෙකු පළමු වරට හමුවෙයි.",
    "අපගේ මොළය එකවරම අපට වෛර කරයි, අපට ආදරය කරයි, අප ගැන සැලකිල්ලක් නොදක්වයි, සහ අපගේ සෑම පියවරක්ම ක්ෂුද්‍ර කළමනාකරණය කරයි.",
    "පිරිමියෙකු වීම උපතේ කාරණයකි. මිනිසෙකු වීම වයස පිළිබඳ කාරණයකි. නමුත් මහත්වරයකු වීම තේරීමකි.",
    "ළමුන් තම ගිණුම් දෙමාපියන්ගෙන් සඟවා තබනවාට වඩා ඉක්මනින් ඔවුන්ගේ සමාජ ගිණුම දරුවන්ගෙන් සඟවනු ඇත.",
    "විකිපීඩියාව යනු අන්තර්ජාලය යනු කුමක්ද යන්නයි.",
    "තේමා උද්‍යානයක් යනු දුරින් කෑගැසීම් ඇසෙන සහ සැලකිලිමත් නොවිය හැකි එකම ස්ථානයයි.",
    "රැහැන් රහිත දුරකථන චාජරයක් රැහැන් රහිත චලනයකට වඩා අඩු නිදහසක් ලබා දෙයි.",
    "ඔබ අකමැති දෙයකට කැමති යැයි ඔබ යමෙකු නැවත නැවතත් විවේචනය කරන්නේ නම්, ඔවුන් එයට කැමති වීම නවත්වන්නේ නැත. ඔවුන් ඔබට කැමති වීම නවත්වයි.",
    "කොහේ හරි ආච්චි කෙනෙක් ඉන්නවා, ඔහුගේ මුනුබුරා ඇත්තටම ලෝකයේ කඩවසම් පිරිමි ළමයා.",
    "කවදා හෝ දවසක මිනිස් දුරකථන හුවමාරුව සැබෑවක් වුවහොත් මිනිසුන් තවමත් වැඩ සඳහා ප්‍රමාද වනු ඇත.",
    "කකුළුවන් ආහාරයට ගත් පළමු මිනිසුන් සන්නාහ සහිත මුහුදු මකුළුවෙකු ආහාරයට ගැනීමට උත්සාහ කළ යුතුය",
    "තනිවම යමක් කිරීම කනගාටුවට කරුණකි, නමුත් එය තනිවම කිරීම සිසිල් ය.",
    "ඔබ යමක් පළ කිරීමෙන් පසු ඔබේ මොළය හදිසියේම සෝදුපත් කියවීමේදී පරිපූර්ණ වේ.",
    "ඔබගේ ධාවන ලැයිස්තුවේ සෑම විටම ඔබ මඟ හැරිය නමුත් ඉවත් නොකරන ගීතයක් තිබේ.",
    "ඊළඟ ශතවර්ෂයේ ළමයින් හොඳ පරිශීලක නාමයන් ගැනීම ගැන අපට වෛර කරනු ඇත.",
    "බුබුලු යනු මිනිසුන්ට වැසි යනු කුමක්දැයි මසුන් ඇල්ලීමයි.",
    "ඔබ වැඩි වැඩියෙන් මුණගැසෙන තරමට, ඔබේ දෙමාපියන් ඔබව හදා වඩා ගත් ආකාරය ඔබ තේරුම් ගෙන අගය කරයි.",
    "කොමාව යනු කෙටි විරාමයකි, කෝමා යනු දිගු විරාමයකි.",
    "කවදා හෝ ඔබ අවදි නොවනු ඇත, නැතහොත් නින්දට නොයනු ඇත.",
    "බර්මියුඩා ත්‍රිකෝණය මෙම සමාකරණයේ පිටවීමේ ද්වාරය විය හැකිය.",
    "අපි වාහන නැවැත්වීමේ ස්ථානයට ඉහළින් සූර්ය පැනල තැබුවහොත් අපගේ මෝටර් රථ උණුසුම් නොවනු ඇති අතර අපට පිරිසිදු ශක්තියක් ලැබෙනු ඇත.",
)

DARE = (
    "Show the most embarrassing photo on your phone",
    "Show the last five people you texted and what the messages said",
    "Let the rest of the group DM someone from your Instagram account",
    "Eat a raw piece of garlic",
    "Do 100 squats",
    "Keep three ice cubes in your mouth until they melt",
    "Say something dirty to the person on your leftYou've got company!",
    "Give a foot massage to the person on your right",
    "Put 10 different available liquids into a cup and drink it",
    "*Yell out the first word that comes to your mind",
    "Give a lap dance to someone of your choice",
    "Remove four items of clothing",
    "Like the first 15 posts on your Facebook newsfeed",
    "Eat a spoonful of mustard",
    "Keep your eyes closed until it's your go again",
    "Send a sext to the last person in your phonebook",
    "Show off your orgasm face",
    "Seductively eat a banana",
    "Empty out your wallet/purse and show everyone what's inside",
    "Do your best sexy crawl",
    "Pretend to be the person to your right for 10 minutes",
    "Eat a snack without using your hands",
    "Say two honest things about everyone else in the group",
    "Twerk for a minute",
    "Try and make the group laugh as quickly as possible",
    "Try to put your whole fist in your mouth",
    "Tell everyone an embarrassing story about yourself",
    "Try to lick your elbow",
    "Post the oldest selfie on your phone on Instagram Stories",
    "Tell the saddest story you know",
    "Howl like a wolf for two minutes",
    "Dance without music for two minutes",
    "Pole dance with an imaginary pole",
    "Let someone else tickle you and try not to laugh",
    "Put as many snacks into your mouth at once as you can",
    "Send your most recent selfie.",
    "Send your ugliest selfie.",
    "Send a screenshot of your facebook search history",
    "Send a screenshot of your gallery.",
    "Send a screenshot of your messenger inbox",
    "Tell something very intimate.",
    "Send a screenshot of your twitter inbox",
    "Send a screenshot of your homescreen.",
    "Send a cover of your favorite song. 🎤",
    "Do a lyric prank on someone and send proof.",
    "Confess to your current crush. ❤️",
    "Declare who is your true love.",
    "Send a screenshot of your gallery.",
    "Set your crush’s picture as your dp.",
    "Suggest me more dares.",
)


# Taken from Openuserbot.
GDNIGHT = [
    "`Good night keep your dreams alive`",
    "`Night, night, to a dear friend! May you sleep well!`",
    "`May the night fill with stars for you. May counting every one, give you contentment!`",
    "`Wishing you comfort, happiness, and a good night’s sleep!`",
    "`Now relax. The day is over. You did your best. And tomorrow you’ll do better. Good Night!`",
    "`Good night to a friend who is the best! Get your forty winks!`",
    "`May your pillow be soft, and your rest be long! Good night, friend!`",
    "`Let there be no troubles, dear friend! Have a Good Night!`",
    "`Rest soundly tonight, friend!`",
    "`Have the best night’s sleep, friend! Sleep well!`",
    "`Have a very, good night, friend! You are wonderful!`",
    "`Relaxation is in order for you! Good night, friend!`",
    "`Good night. May you have sweet dreams tonight.`",
    "`Sleep well, dear friend and have sweet dreams.`",
    "`As we wait for a brand new day, good night and have beautiful dreams.`",
    "`Dear friend, I wish you a night of peace and bliss. Good night.`",
    "`Darkness cannot last forever. Keep the hope alive. Good night.`",
    "`By hook or crook you shall have sweet dreams tonight. Have a good night, buddy!`",
    "`Good night, my friend. I pray that the good Lord watches over you as you sleep. Sweet dreams.`",
    "`Good night, friend! May you be filled with tranquility!`",
    "`Wishing you a calm night, friend! I hope it is good!`",
    "`Wishing you a night where you can recharge for tomorrow!`",
    "`Slumber tonight, good friend, and feel well rested, tomorrow!`",
    "`Wishing my good friend relief from a hard day’s work! Good Night!`",
    "`Good night, friend! May you have silence for sleep!`",
    "`Sleep tonight, friend and be well! Know that you have done your very best today, and that you will do your very best, tomorrow!`",
    "`Friend, you do not hesitate to get things done! Take tonight to relax and do more, tomorrow!`",
    "`Friend, I want to remind you that your strong mind has brought you peace, before. May it do that again, tonight! May you hold acknowledgment of this with you!`",
    "`Wishing you a calm, night, friend! Hoping everything winds down to your liking and that the following day meets your standards!`",
    "`May the darkness of the night cloak you in a sleep that is sound and good! Dear friend, may this feeling carry you through the next day!`",
    "`Friend, may the quietude you experience tonight move you to have many more nights like it! May you find your peace and hold on to it!`",
    "`May there be no activity for you tonight, friend! May the rest that you have coming to you arrive swiftly! May the activity that you do tomorrow match your pace and be all of your own making!`",
    "`When the day is done, friend, may you know that you have done well! When you sleep tonight, friend, may you view all the you hope for, tomorrow!`",
    "`When everything is brought to a standstill, friend, I hope that your thoughts are good, as you drift to sleep! May those thoughts remain with you, during all of your days!`",
    "`Every day, you encourage me to do new things, friend! May tonight’s rest bring a new day that overflows with courage and exciting events!`",
]

# Taken from Openuserbot.
GDMORNING = [
    "`Life is full of uncertainties. But there will always be a sunrise after every sunset. Good morning!`",
    "`It doesn’t matter how bad was your yesterday. Today, you are going to make it a good one. Wishing you a good morning!`",
    "`If you want to gain health and beauty, you should wake up early. Good morning!`",
    "`May this morning offer you new hope for life! May you be happy and enjoy every moment of it. Good morning!`",
    "`May the sun shower you with blessings and prosperity in the days ahead. Good morning!`",
    "`Every sunrise marks the rise of life over death, hope over despair and happiness over suffering. Wishing you a very enjoyable morning today!`",
    "`Wake up and make yourself a part of this beautiful morning. A beautiful world is waiting outside your door. Have an enjoyable time!`",
    "`Welcome this beautiful morning with a smile on your face. I hope you’ll have a great day today. Wishing you a very good morning!`",
    "`You have been blessed with yet another day. What a wonderful way of welcoming the blessing with such a beautiful morning! Good morning to you!`",
    "`Waking up in such a beautiful morning is a guaranty for a day that’s beyond amazing. I hope you’ll make the best of it. Good morning!`",
    "`Nothing is more refreshing than a beautiful morning that calms your mind and gives you reasons to smile. Good morning! Wishing you a great day.`",
    "`Another day has just started. Welcome the blessings of this beautiful morning. Rise and shine like you always do. Wishing you a wonderful morning!`",
    "`Wake up like the sun every morning and light up the world your awesomeness. You have so many great things to achieve today. Good morning!`",
    "`A new day has come with so many new opportunities for you. Grab them all and make the best out of your day. Here’s me wishing you a good morning!`",
    "`The darkness of night has ended. A new sun is up there to guide you towards a life so bright and blissful. Good morning dear!`",
    "`Wake up, have your cup of morning tea and let the morning wind freshen you up like a happiness pill. Wishing you a good morning and a good day ahead!`",
    "`Sunrises are the best; enjoy a cup of coffee or tea with yourself because this day is yours, good morning! Have a wonderful day ahead.`",
    "`A bad day will always have a good morning, hope all your worries are gone and everything you wish could find a place. Good morning!`",
    "`A great end may not be decided but a good creative beginning can be planned and achieved. Good morning, have a productive day!`",
    "`Having a sweet morning, a cup of coffee, a day with your loved ones is what sets your “Good Morning” have a nice day!`",
    "`Anything can go wrong in the day but the morning has to be beautiful, so I am making sure your morning starts beautiful. Good morning!`",
    "`Open your eyes with a smile, pray and thank god that you are waking up to a new beginning. Good morning!`",
    "`Morning is not only sunrise but A Beautiful Miracle of God that defeats the darkness and spread light. Good Morning.`",
    "`Life never gives you a second chance. So, enjoy every bit of it. Why not start with this beautiful morning. Good Morning!`",
    "`If you want to gain health and beauty, you should wake up early. Good Morning!`",
    "`Birds are singing sweet melodies and a gentle breeze is blowing through the trees, what a perfect morning to wake you up. Good morning!`",
    "`This morning is so relaxing and beautiful that I really don’t want you to miss it in any way. So, wake up dear friend. A hearty good morning to you!`",
    "`Mornings come with a blank canvas. Paint it as you like and call it a day. Wake up now and start creating your perfect day. Good morning!`",
    "`Every morning brings you new hopes and new opportunities. Don’t miss any one of them while you’re sleeping. Good morning!`",
    "`Start your day with solid determination and great attitude. You’re going to have a good day today. Good morning my friend!`",
    "`Friendship is what makes life worth living. I want to thank you for being such a special friend of mine. Good morning to you!`",
    "`A friend like you is pretty hard to come by in life. I must consider myself lucky enough to have you. Good morning. Wish you an amazing day ahead!`",
    "`The more you count yourself as blessed, the more blessed you will be. Thank God for this beautiful morning and let friendship and love prevail this morning.`",
    "`Wake up and sip a cup of loving friendship. Eat your heart out from a plate of hope. To top it up, a fork full of kindness and love. Enough for a happy good morning!`",
    "`It is easy to imagine the world coming to an end. But it is difficult to imagine spending a day without my friends. Good morning.`",
]

# Abuse strings credits @NotAMemeBot
ABUSE_STRINGS = (
    "Owww ... Such a stupid idiot.",
    "Don't drink and type.",
    "I think you should go home or better a mental asylum.",
    "Command not found. Just like your brain.",
    "Do you realize you are making a fool of yourself? Apparently not.",
    "You can type better than that.",
    "Bot rule 544 section 9 prevents me from replying to stupid humans like you.",
    "Sorry, we do not sell brains.",
    "Believe me you are not normal.",
    "I bet your brain feels as good as new, seeing that you never use it.",
    "If I wanted to kill myself I'd climb your ego and jump to your IQ.",
    "Zombies eat brains... you're safe.",
    "You didn't evolve from apes, they evolved from you.",
    "Come back and talk to me when your I.Q. exceeds your age.",
    "I'm not saying you're stupid, I'm just saying you've got bad luck when it comes to thinking.",
    "What language are you speaking? Cause it sounds like bullshit.",
    "Stupidity is not a crime so you are free to go.",
    "You are proof that evolution CAN go in reverse.",
    "I would ask you how old you are but I know you can't count that high.",
    "As an outsider, what do you think of the human race?",
    "Brains aren't everything. In your case they're nothing.",
    "Ordinarily people live and learn. You just live.",
    "I don't know what makes you so stupid, but it really works.",
    "Keep talking, someday you'll say something intelligent! (I doubt it though)",
    "Shock me, say something intelligent.",
    "Your IQ's lower than your shoe size.",
    "Alas! Your neurotransmitters are no more working.",
    "Are you crazy you fool.",
    "Everyone has the right to be stupid but you are abusing the privilege.",
    "I'm sorry I hurt your feelings when I called you stupid. I thought you already knew that.",
    "You should try tasting cyanide.",
    "Your enzymes are meant to digest rat poison.",
    "You should try sleeping forever.",
    "Pick up a gun and shoot yourself.",
    "You could make a world record by jumping from a plane without parachute.",
    "Stop talking BS and jump in front of a running bullet train.",
    "Try bathing with Hydrochloric Acid instead of water.",
    "Try this: if you hold your breath underwater for an hour, you can then hold it forever.",
    "Go Green! Stop inhaling Oxygen.",
    "God was searching for you. You should leave to meet him.",
    "give your 100%. Now, go donate blood.",
    "Try jumping from a hundred story building but you can do it only once.",
    "You should donate your brain seeing that you never used it.",
    "Volunteer for target in an firing range.",
    "Head shots are fun. Get yourself one.",
    "You should try swimming with great white sharks.",
    "You should paint yourself red and run in a bull marathon.",
    "You can stay underwater for the rest of your life without coming back up.",
    "How about you stop breathing for like 1 day? That'll be great.",
    "Try provoking a tiger while you both are in a cage.",
    "Have you tried shooting yourself as high as 100m using a canon.",
    "You should try holding TNT in your mouth and igniting it.",
    "Try playing catch and throw with RDX its fun.",
    "I heard phogine is poisonous but i guess you wont mind inhaling it for fun.",
    "Launch yourself into outer space while forgetting oxygen on Earth.",
    "You should try playing snake and ladders, with real snakes and no ladders.",
    "Dance naked on a couple of HT wires.",
    "Active Volcano is the best swimming pool for you.",
    "You should try hot bath in a volcano.",
    "Try to spend one day in a coffin and it will be yours forever.",
    "Hit Uranium with a slow moving neutron in your presence. It will be a worthwhile experience.",
    "You can be the first person to step on sun. Have a try.",
)

RUN_STRINGS = (
    "Where do you think you're going?",
    "Huh? what? did they get away?",
    "ZZzzZZzz... Huh? what? oh, just them again, nevermind.",
    "Get back here!",
    "Not so fast...",
    "Look out for the wall!",
    "Don't leave me alone with them!!",
    "You run, you die.",
    "Jokes on you, I'm everywhere",
    "You're gonna regret that...",
    "You could also try /kickme, I hear that's fun.",
    "Go bother someone else, no-one here cares.",
    "You can run, but you can't hide.",
    "Is that all you've got?",
    "I'm behind you...",
    "You've got company!",
    "We can do this the easy way, or the hard way.",
    "You just don't get it, do you?",
    "Yeah, you better run!",
    "Please, remind me how much I care?",
    "I'd run faster if I were you.",
    "That's definitely the droid we're looking for.",
    "May the odds be ever in your favour.",
    "Famous last words.",
    "And they disappeared forever, never to be seen again.",
    '"Oh, look at me! I\'m so cool, I can run from a bot!" - this person',
    "Yeah yeah, just tap /kickme already.",
    "Here, take this ring and head to Mordor while you're at it.",
    "Legend has it, they're still running...",
    "Unlike Harry Potter, your parents can't protect you from me.",
    "Fear leads to anger. Anger leads to hate. Hate leads to suffering. If you keep running in fear, you might "
    "be the next Vader.",
    "Multiple calculations later, I have decided my interest in your shenanigans is exactly 0.",
    "Legend has it, they're still running.",
    "Keep it up, not sure we want you here anyway.",
    "You're a wiza- Oh. Wait. You're not Harry, keep moving.",
    "NO RUNNING IN THE HALLWAYS!",
    "Hasta la vista, baby.",
    "Who let the dogs out?",
    "It's funny, because no one cares.",
    "Ah, what a waste. I liked that one.",
    "Frankly, my dear, I don't give a damn.",
    "My milkshake brings all the boys to yard... So run faster!",
    "You can't HANDLE the truth!",
    "A long time ago, in a galaxy far far away... Someone would've cared about that. Not anymore though.",
    "Hey, look at them! They're running from the inevitable banhammer... Cute.",
    "Han shot first. So will I.",
    "What are you running after, a white rabbit?",
    "As The Doctor would say... RUN!",
)


# pat - by @saitamarobot
PAT_TEMPLATES = (
    "Pattt Se Headshot!",
    "{user1} pats {user2} on the head.",
    "*gently rubs {user2}'s head*.",
    "*{user1} mofumofus {user2}'s head*",
    "*{user1} messes up {user2}'s head*",
    "*{user1} intensly rubs {user2}'s head*",
    "*{user2}'s waifu pats their head*",
    "*{user2}'s got free headpats*",
    "No pats for {user2}!",
    "Oh no! We are all out of pats.",
    "This is a designated no pat zone!",
    "{user1} spoils {user2} with headpats!",
    "{user2} received one free headpat!",
    "{user1} headpats {user2} whilst giving a lap pillow",
    "{user1} aggressively pats {user2}",
    "{user1} gently strokes {user2}'s head",
    "Pat, pat, pat, pat",
    "{user2} could not escape {user1}'s headpats",
    "{user1} rubs {user2} on the neck",
    "Must... extort... HEADPATS",
    "{user1} headpats {user2}'s head with a pat",
    "{user1} pats {user2} unexpectedly",
    "{user1} pats {user2} with consent, maybe?",
    "Pat pat, {user2} honto kawaii ne!",
    "{user1} headpats {user2} at 420apm",
    "{user1} bellyrubs {user2}",
    "{user1} pats {user2} friendlily",
    "{user2} uses HEADPATS? O KAWAII KOTO",
    "(*´ω´(*｀ω｀)",
    "(ｏ・_・)ノ”(ᴗ_ ᴗ。)",
    "(*￣▽￣)ノ”(- -*)",
    "(っ´ω`)ﾉ(╥ω╥)",
    "( ´Д｀)ﾉ(´･ω･`) ﾅﾃﾞﾅﾃﾞ",
)

PAT_GIFS = (
    "CgACAgQAAxkBAAIByV--JhjY9HrIzpRnYY3KKvAgfc5CAAJHAgACOvCNUjkBPKk8gG_QHgQ",
    "CgACAgQAAxkBAAIByF--JhiD_dRrZDN-aYMpi-s_-omHAAJcAgACDY6EUjMkLsa2rXTXHgQ",
    "CgACAgQAAx0CSxgUbQACJf9f4W4bq_BWoHgMjTzSLBIx0RO0awACygYAAiYNiFPz3-km0vNPWR4E",
    "CgACAgQAAx0CSxgUbQACJfpf4W4IIBVwRXeSvSTcunixHFzmtQACagIAAv0FLVNvZ_FCfNrvsR4E",
    "CgACAgQAAxkBAAIBx1--JhhEaEdSqi4mQiwzyN1egkZ8AAIjAgACNyiMUozDfqiw_yObHgQ",
    "CgACAgQAAxkBAAIBxl--JhimxY9FVs2LYRhNYE41V2fGAAIUAgACTF2MUtgrqDLvmUVeHgQ",
    "CgACAgQAAxkBAAIB0l--JqKztJB24eqJLe8mfPPPYVDhAAIVAgACeVbVUnaV3UIO1KK-HgQ",
)

PAT_STICKERS = (
    "CAACAgQAAxkBAAICYl--eHbgPobSdk9Tj4nSxleQ0TdJAAKvAAPVMzML3OVCdzeQd1seBA",
    "CAACAgQAAxkBAAICY1--eHfZk1pwGb_EJb6Dj3ep8LJfAAKtAAPVMzMLgmD0afnZcfIeBA",
    "CAACAgQAAxkBAAICZF--eHlF0n4mZo2M3CaYu2OU013VAAK1AAPVMzMLs-0qSivU6JweBA",
    "CAACAgQAAxkBAAICZl--eH28owxPadJ0HOfmVTiltdCYAAK7AAPVMzML2w_RrJI2ClweBA",
    "CAACAgQAAxkBAAICZ1--eH3JMYs3KFC_eVjdtQfClgUfAAK9AAPVMzML0XUtOSPmUKIeBA",
    "CAACAgQAAxkBAAICaF--eH4dBpnjndfqXPCGhTngt-OIAAK_AAPVMzMLHdlAuFtjtSUeBA",
    "CAACAgQAAxkBAAICaV--eH-zmpo-ykUzRDJ-jWraxfQmAALDAAPVMzMLHlxOVFgekGEeBA",
    "CAACAgQAAxkBAAICal--eIEpEdc9Gk5OqzZVsVnOGGaRAALFAAPVMzMLX8y0ifckrQ8eBA",
    "CAACAgQAAxkBAAICa1--eIHWTj20mbxn0wc4qfZBqWiXAALHAAPVMzMLz_FARSAVUQUeBA",
    "CAACAgQAAxkBAAICbF--eJDiZYA6aRndG9upuR2_XfIgAAMBAALVMzML55oysf4qBxgeBA",
    "CAACAgQAAxkBAAICbV--eJLtLbJrqeKgG5lllQ2gqlCcAAL6AAPVMzMLKhav7ii41zQeBA",
    "CAACAgQAAxkBAAICbl--eJVJO_moWtoktLrg3jzUaeTkAAJ_AQAC1TMzCy8SeosY4uaXHgQ",
    "CAACAgQAAxkBAAICb1--eJVMMK6yxFEWF92K5jr4eG0EAAKCAQAC1TMzC87tPZLqbwkSHgQ",
    "CAACAgQAAxkBAAICcF--eJbOrVL_MkJo5kw_zfIS4TEzAAI6AQAC1TMzC3h8vVt-_pjtHgQ",
    "CAACAgQAAxkBAAICcV--eJb1nknGXwKgGE5aXDcawgK3AAJ6AQAC1TMzCweeI_mdwBUIHgQ",
    "CAACAgQAAxkBAAICcl--eJk_0PxzYNwy1TZ5IWwsW__sAAKyAQAC1TMzC-yfrpJDR9k7HgQ",
)


# SLAP_TEMPLATES From @Hexzy
SLAP_TEMPLATES = (
    "{user2} was shot by {user1}.",
    "{user2} walked into a cactus while trying to escape {user1}.",
    "{user2} drowned whilst trying to escape {user1}.",
    "{user2} fell into a patch of cacti.",
    "{user2} went up in flames.",
    "{user2} burned to death.",
    "{user2} was burnt to a crisp whilst fighting {user1}.",
    "{user2} was struck by lightning.",
    "{user2} was slain by {user1}.",
    "{user2} was killed by magic.",
    "{user2} starved to death.",
    "{user2} fell out of the world.",
    "{user2} was knocked into the void by {user1}.",
    "{user2}'s bones are scraped clean by the desolate wind.",
    "{user2} fainted.",
    "{user2} is out of usable Pokemon! {user2} whited out!.",
    "{user2} is out of usable Pokemon! {user2} blacked out!.",
    "{user2} says goodbye to this cruel world.",
    "{user2} got rekt.",
    "{user2} was sawn in half by {user1}.",
    "{user2}'s melon was split by {user1}.",
    "{user2} was sliced and diced by {user1}.",
    "{user2}'s death put another notch in {user1}'s axe.",
    "{user2} died from {user1}'s mysterious tropical disease.",
    "{user2} played hot-potato with a grenade.",
    "{user2} was knifed by {user1}.",
    "{user2} ate a grenade.",
    "{user2} is what's for dinner!",
    "{user2} was terminated by {user1}.",
    "{user2} was shot before being thrown out of a plane.",
    "{user2} has encountered an error.",
    "{user2} died and reincarnated as a goat.",
    "{user1} threw {user2} off a building.",
    "{user2} got a premature burial.",
    "{user1} spammed {user2}'s email.",
    "{user1} hit {user2} with a small, interstellar spaceship.",
    "{user1} put {user2} in check-mate.",
    "{user1} RSA-encrypted {user2} and deleted the private key.",
    "{user1} put {user2} in the friendzone.",
    "{user1} slaps {user2} with a DMCA takedown request!",
    "{user2} died of hospital gangrene.",
    "{user2} got a house call from Doctor {user1}.",
    "{user1} beheaded {user2}.",
    "{user2} got stoned...by an angry mob.",
    "{user1} sued the pants off {user2}.",
    "{user2} was one-hit KO'd by {user1}.",
    "{user1} sent {user2} down the memory hole.",
    "{user2} was a mistake. - '{user1}' ",
    "{user1} checkmated {user2} in two moves.",
    "{user2} was made redundant.",
    "{user1} {hits} {user2} with a bat!.",
    "{user1} {hits} {user2} with a Taijutsu Kick!.",
    "{user1} {hits} {user2} with X-Gloves!.",
    "{user1} {hits} {user2} with a Jet Punch!.",
    "{user1} {hits} {user2} with a Jet Pistol!.",
    "{user1} {hits} {user2} with a United States of Smash!.",
    "{user1} {hits} {user2} with a Detroit Smash!.",
    "{user1} {hits} {user2} with a Texas Smash!.",
    "{user1} {hits} {user2} with a California Smash!.",
    "{user1} {hits} {user2} with a New Hampshire Smash!.",
    "{user1} {hits} {user2} with a Missouri Smash!.",
    "{user1} {hits} {user2} with a Carolina Smash!.",
    "{user1} {hits} {user2} with a King Kong Gun!.",
    "{user1} {hits} {user2} with a baseball bat - metal one.!.",
    "*Serious punches {user2}*.",
    "*Normal punches {user2}*.",
    "*Consecutive Normal punches {user2}*.",
    "*Two Handed Consecutive Normal Punches {user2}*.",
    "*Ignores {user2} to let them die of embarassment*.",
    "*points at {user2}* What's with this sassy... lost child?.",
    "*Hits {user2} with a Fire Tornado*.",
    "{user1} pokes {user2} in the eye !",
    "{user1} pokes {user2} on the sides!",
    "{user1} pokes {user2}!",
    "{user1} pokes {user2} with a needle!",
    "{user1} pokes {user2} with a pen!",
    "{user1} pokes {user2} with a stun gun!",
    "{user2} is secretly a Furry!.",
    "Hey Everybody! {user1} is asking me to be mean!",
    "( ･_･)ﾉ⌒●~* (･.･;) <-{user2}",
    "Take this {user2}\n(ﾉﾟДﾟ)ﾉ ))))●~* ",
    "Here {user2} hold this\n(｀・ω・)つ ●~＊",
    "( ・_・)ノΞ●~*  {user2},Shinaeeeee!!.",
    "( ・∀・)ｒ鹵~<≪巛;ﾟДﾟ)ﾉ\n*Bug sprays {user2}*.",
    "( ﾟДﾟ)ﾉ占~<巛巛巛.\n-{user2} You pest!",
    "( う-´)づ︻╦̵̵̿╤── \(˚☐˚”)/ {user2}.",
    "{user1} {hits} {user2} with a {item}.",
    "{user1} {hits} {user2} in the face with a {item}.",
    "{user1} {hits} {user2} around a bit with a {item}.",
    "{user1} {throws} a {item} at {user2}.",
    "{user1} grabs a {item} and {throws} it at {user2}'s face.",
    "{user1} launches a {item} in {user2}'s general direction.",
    "{user1} starts slapping {user2} silly with a {item}.",
    "{user1} pins {user2} down and repeatedly {hits} them with a {item}.",
    "{user1} grabs up a {item} and {hits} {user2} with it.",
    "{user1} ties {user2} to a chair and {throws} a {item} at them.",
    "{user1} gave a friendly push to help {user2} learn to swim in lava.",
    "{user1} bullied {user2}.",
    "Nyaan ate {user2}'s leg. *nomnomnom*",
    "{user1} {throws} a master ball at {user2}, resistance is futile.",
    "{user1} hits {user2} with an action beam...bbbbbb (ง・ω・)ง ====*",
    "{user1} ara ara's {user2}.",
    "{user1} ora ora's {user2}.",
    "{user1} muda muda's {user2}.",
    "{user2} was turned into a Jojo reference!",
    "{user1} hits {user2} with {item}.",
    "Round 2!..Ready? .. FIGHT!!",
)

ITEMS = (
    "cast iron skillet",
    "angry meow",
    "cricket bat",
    "wooden cane",
    "shovel",
    "toaster",
    "book",
    "laptop",
    "rubber chicken",
    "spiked bat",
    "heavy rock",
    "chunk of dirt",
    "ton of bricks",
    "rasengan",
    "spirit bomb",
    "100-Type Guanyin Bodhisattva",
    "rasenshuriken",
    "Murasame",
    "ban",
    "chunchunmaru",
    "Kubikiribōchō",
    "rasengan",
    "spherical flying kat",
)

THROW = (
    "throws",
    "flings",
    "chucks",
    "hurls",
)

HIT = (
    "hits",
    "whacks",
    "slaps",
    "smacks",
    "bashes",
    "pats",
)

PUNCH_TEMPLATES = (
    "{user1} {punches} {user2} with a {item}.",
    "{user1} {punches} {user2} in the face with a {item}.",
    "{user1} {punches} {user2} around a bit with a {item}.",
    "{user1} {punches} {user2} on their face. 👊",
)

HUG_TEMPLATES = (
    "{user1} {hug} {user2}.",
    "{user1} {hug} {user2} warmly.",
    "{user1} {hug} {user2} with a love. 💘",
    "{user1} {hug} {user2} with kindness.",
)

PUNCH = (
    "punch",
    "punched",
    "smack",
)

HUG = ("hugs", "hugged", "kissed", "pinches")

# Table strings credits: @Hexzy

TABLE = (
    "╬@GangOfMafiaTeam\n╬@Mafia_Update",
    "I ran out of tables, will order more.",
    "Go do some work instead of flippin tables.",
)

GBUN = (
    "Beware! This Bot-Admeme Can Gbun You Right Off The Map.",
    "I Guess You've Forgot Spelling Of GBAN Maybe...?",
    "Don't Misuse Your Powers...",
    "Nah, He Looks Innocent...",
)


GBAM = "<b>Beginning Of Global Bam For {user2}</b>  \n \nChat Id : <code>{chatid}</code> \nReason : <i>{reason}</i> \nGBammed By {user1}"


GBAM_REASON = (
    "sasta noob",
    "sasta waifu stealer",
    "sasta white-het hekur",
    "sasta white-het codur",
    "sasta white-het vala chintu",
    "sasta hexa hekur",
    "sasta hexa playur",
    "sasta tiktokur💃🏾",
    "sasta membor of team 7",
    "sasta selmon boi",
    "sasta fri-fire player",
    "sasta chhota bhim",
    "sasta chhapri",
    "sasta jony sin",
    "sasta chhapri nibba",
    "sasta nibba",
    "sasti ria chokroborti",
    "sasti nibbi",
    "sasta camper",
)


GIFS = [
    "CgACAgQAAx0ESlgI7AACAqxfu09m1qXPJjRiyRMyJxswdUA5LwACaAgAAlZD0VEtI5O_RO_rSB4E",
    "CgACAgUAAx0CSlgI7AACA2Ffu4L_5S3dL5YUWNGBEBL60oBNIgACqwADg_8wVe6pdZO2-TIxHgQ",
    "CgACAgQAAx0ESlgI7AACA3Nfu4M3oUQUhZ6X-I5LNrQkWJ1iogACaAgAAlZD0VGB9mP1VKDQJR4E",
]


DECIDE = ("Yes.", "NoU.", "Maybe.", "No.")


# AFK strings credits: PaperPlaneExtended!
AFKRPL = (
    "<b>{}</b> is busy right now. Please talk in a bag and when they come back you can just give him the bag!",
    "<b>{}</b> is away right now. If you need anything, leave a message after the beep:\n<code>beeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeep</code>!",
    "You just missed <b>{}</b>, next time aim better.",
    "{} will be back in a few minutes and if not...,\nwait longer.",
    "Roses are red,\nViolets are blue,\nLeave me a message,\nAnd {} will get back to you.",
    "If you haven't figured it out already,\n{} is not here.",
    "{} went that way\n---->",
    "{} went went this way\n<----",
    "{} is not here so stop writing to them,\nor else you will find yourself with a screen full of your own messages.",
    "Life is so short, there are so many things to do...\n{} is away doing one of them..",
    "{} is away from the keyboard at the moment, but if you'll scream loud enough at your screen, they might just hear you.",
)

NOAFK = (
    "{} ආපහු ඔන්ලයින් ආවෝ . . . ",
    "{} is back Alive!",
)

AFK = (
    "මම දැන් ටිකකට Offline  👋 {}!",
    "🙈",
    "See you later {}!",
    "🤫",
    "මම දැන් ඔන්ලයින් නෑ ඉක්මනින් ඔන්ලයින් එන්නම්  {}!",
    "🌝",
)

SHGS = (
    "┐(´д｀)┌",
    "┐(´～｀)┌",
    "┐(´ー｀)┌",
    "┐(￣ヘ￣)┌",
    "╮(╯∀╰)╭",
    "╮(╯_╰)╭",
    "┐(´д`)┌",
    "┐(´∀｀)┌",
    "ʅ(́◡◝)ʃ",
    "┐(ﾟ～ﾟ)┌",
    "┐('д')┌",
    "┐(‘～`;)┌",
    "ヘ(´－｀;)ヘ",
    "┐( -“-)┌",
    "ʅ（´◔౪◔）ʃ",
    "ヽ(゜～゜o)ノ",
    "ヽ(~～~ )ノ",
    "┐(~ー~;)┌",
    "┐(-。ー;)┌",
    r"¯\_(ツ)_/¯",
    r"¯\_(⊙_ʖ⊙)_/¯",
    r"¯\_༼ ಥ ‿ ಥ ༽_/¯",
    "乁( ⁰͡  Ĺ̯ ⁰͡ ) ㄏ",
)

CRI = (
    "أ‿أ",
    "╥﹏╥",
    "(;﹏;)",
    "(ToT)",
    "(┳Д┳)",
    "(ಥ﹏ಥ)",
    "（；へ：）",
    "(T＿T)",
    "（πーπ）",
    "(Ｔ▽Ｔ)",
    "(⋟﹏⋞)",
    "（ｉДｉ）",
    "(´Д⊂ヽ",
    "(;Д;)",
    "（>﹏<）",
    "(TдT)",
    "(つ﹏⊂)",
    "༼☯﹏☯༽",
    "(ノ﹏ヽ)",
    "(ノAヽ)",
    "(╥_╥)",
    "(T⌓T)",
    "(༎ຶ⌑༎ຶ)",
    "(☍﹏⁰)｡",
    "(ಥ_ʖಥ)",
    "(つд⊂)",
    "(≖͞_≖̥)",
    "(இ﹏இ`｡)",
    "༼ಢ_ಢ༽",
    "༼ ༎ຶ ෴ ༎ຶ༽",
)


BEING_LOGICAL = (
    "දිය යට බුබුලු සහ වැහි බිංදු එකිනෙකට ප්‍රතිවිරුද්ධ දෙයකි",
    "ඔබ මකන්නෙකු මිලට ගන්නේ නම් ඔබ වචනාර්ථයෙන් ඔබේ වැරදි සඳහා ගෙවනු ලැබේ.",
    "මිනිසුන් සඳ මත ජනපදකරණය කරයි, එය බොහෝ විට විශ්‍රාමික නිවාස ආකර්ෂණය කර ගනු ඇත, මන්ද දුර්වල ගුරුත්වාකර්ෂණය නිසා වැඩිහිටියන්ට ශක්තිමත් බවක් දැනෙනු ඇත.",
    "ඔබ වැඩිපුරම සැලකිලිමත් වන පුද්ගලයාට ඔබව වඩාත්ම විනාශ කිරීමේ හැකියාව ඇත.",
    "මාතෘකාව තුළ “ඒ සඳහා රැඳී සිටින්න” සහිත ඕනෑම වීඩියෝවක් ඉතා දිගු වේ.",
    "ඔබේ වයස අවුරුදු ගණන ඔබ සූර්යයා වටා කොපමණ වාරයක් රවුම් කර ඇත්ද, නමුත් මාස ගණනක් තුළ ඔබේ වයස වන්නේ සඳ ඔබව කොපමණ වාරයක් රවුම් කර ඇත්ද යන්නයි.",
    "ආහාර ගැනීමේදී ඔබේ දිව සපාකෑම දශක ගණනාවක අත්දැකීම් සහිතව වුවද ඔබට තවමත් ඉස්කුරුප්පු කළ හැකි ආකාරය පිළිබඳ කදිම නිදසුනකි.",
    "ඔබේ නිවස බල ගැන්වී ඇත්තේ සැතපුම් මිලියන 93 ක් දුරින් පිහිටි රැහැන් රහිත න්‍යෂ්ටික විලයන ප්‍රතික්‍රියාකාරකයකිනි. ඔබේ වහලයේ සූර්ය පැනල ඇති බව පැවසීමට වඩා සිසිල් ය.",
    "වඩාත්ම තැතිගන්වන හැඟීම නම් යමෙකු වීථියේදී ඔබට සිනාසෙන අතර ඔබ සිනාසීමට තරම් වේගයෙන් ප්‍රතික්‍රියා නොකරන විටය.",
    "ජීවත්ව සිටින විට දිරාපත්වීම වැළැක්වීම සඳහා දත් නිරන්තරයෙන් නඩත්තු කිරීම අවශ්‍ය වන නමුත් පොසිල ලෙස තැන්පත් කර වසර දහස් ගණනක් ජීවත් වීමට ඒවා සමත් වේ.",
    "ෆෝල්ඩරයක් යනු ඔබට නැවීමට අවශ්‍ය නැති දේවල් සඳහා ය.",
    "සමහර විට උදේ අවදි වීමෙන් ඔබ නැරඹීමෙන් ඉවත් වීමට තීරණය කළ ජරා චිත්‍රපටයක් නැවත ආරම්භ කිරීමක් මෙන් දැනේ.",
    "සෑම දෙයක්ම සුමටව සිදුවුවහොත්, ඔබට අද මතක නැත.",
    "සැබෑ ජීවිතයේ දී ඔබ නව පුද්ගලයින් මුණගැසෙන විට, ඔබේ සිහින ලෝකය සඳහා තවත් චරිත අගුළු හරිනු ඇත.",
    "සමහර විට ඔවුන් සන්ස්ක්‍රීන් “පිළිකා නාශක ක්‍රීම්” ලෙස නම් කළහොත් වැඩි පිරිසක් එය පැළඳ සිටී.",
    "මීට වසර 200 කට පෙර, මිනිසුන් නිහ ly ව වීදුරු මත තට්ටු කිරීමෙන් සන්නිවේදනය කරනු ඇතැයි මිනිසුන් කිසි විටෙකත් අනුමාන නොකරනු ඇත.",
    "දෙමව්පියන් තම පුතුන් බාගත කරන දේ ගැන කනස්සල්ලට පත්වන අතර තම දියණියන් උඩුගත කරන දේ ගැන කරදර වෙති.",
    "ඔබ යමෙකුගේ වයසට සමාන වන්නේ කෙසේද යන්න පිස්සුවකි, නමුත් ඔබේ ජීවිතයේ සම්පූර්ණයෙන්ම වෙනස් අවධියක.",
    "ඔයාට මැරෙන්න ඕනේ කියලා හිතනකොට, ඔයාට ඇත්තටම මැරෙන්න ඕන නෑ, ඔයාට මේ විදියට ජීවත් වෙන්න ඕන නෑ.",
    "තාක්ෂණික වශයෙන්, කිසිවෙකු මෙතෙක් හිස් කාමරයක නොසිටියේය.",
    "ළූණු යනු ආහාරයේ බාස් වාදකයයි. ඔබ එය තනිවම භුක්ති විඳින්නේ නැත, නමුත් එය එහි නොතිබුනේ නම් ඔබට එය මග හැරෙනු ඇත.",
    "අපි ඇවිදින්න කම්මැලි නිසා අපි කම්මැලි නිසා ඔවුන් ගමන් කිරීමට කම්මැලි නිසා වීඩියෝ ගේම්ස් හි සෑම තැනකම ධාවනය කරමු, නමුත් සැබෑ ජීවිතයේ අපි සෑම තැනකම ඇවිදිමින් සිටියෙමු.",
    "ඔබ විසින් සාදන ලද සෑම තීරණයක්ම මෙම වාක්යය කියවීමට ඔබව ගෙන ආවේය.",
    " නිහඬ වෙන්න  යන වචනය බොහෝ විට ඉතා හයියෙන් කියනු ලැබේ.",
    "සෑම කෙනෙකුම ඔබ වෙහෙස මහන්සි වී වැඩ කිරීමට කැමතියි, නමුත් ඔබ කොතරම් වෙහෙස මහන්සි වී වැඩ කරනවාද යන්න කිසිවෙකුට ඇසීමට අවශ්‍ය නැත.",
    "අපි සැරයටියක් මත හිසකෙස්වලින් දත් මදින්නෙමු.",
    "ඔබගේ අමුතු අවස්ථා කිසිවෙකුට මතක නැත, නමුත් ඔවුන් කාර්යබහුල වන්නේ ඔවුන්ගේම මතක තබා ගැනීමෙනි.",
    "ගොළු අය සරල අදහස් හැකිතාක් සංකීර්ණ ලෙස පැවසීමට උත්සාහ කරන අතර බුද්ධිමත් අය සංකීර්ණ අදහස් හැකිතාක් සරල ලෙස පැවසීමට උත්සාහ කරති.",
    "සමහර අය සිතන්නේ ඔවුන් ඔබට වඩා හොඳ බවයි. සමහර අය සිතන්නේ ඔවුන් දුප්පත් නිසා ඔවුන් ඔබට වඩා හොඳ බවයි.",
    "ලොකුම උත්ප්‍රාසය වන්නේ කාලය ඉතිරි කර ගැනීම සඳහා පරිගණක සහ ජංගම දුරකථන නිර්මාණය කිරීමයි!",
    "මී පැණි ප්‍රථම වරට සොයාගත් පසු, කෘමීන්ගෙන් ලබා ගත හැකි ඕනෑම රොන්මඩයක් මිනිසුන් රස පරීක්‍ෂා කරන කාලයක් තිබෙන්නට ඇත.",
    "ඔබ ඔවුන්ව කලකිරීමට පත් කරනවා වෙනුවට ඔබේ දෙමාපියන් ඔබව කලකිරීමට පත් කරන විට ඔබ වයසට යන බව ඔබ දන්නවා.",
    "මිනිසුන් නිර්මාණය කර ඇත්තේ අත්දැකීම් තුළින් ඉගෙනීම සඳහා වන අතර අධ්‍යාපන ක්‍රමය විසින් එය සකස් කර ඇති බැවින් අපට අත්දැකීම් නොලැබේ.",
    "දිලිසීම කෙරෙහි අවධානය යොමු කිරීමෙන්, ඔබ සෙමෙන් සෙමෙන් ඇසේ ... හුස්ම ගැනීමට සමාන වේ.",
    "රථවාහන තදබදයට ඉක්මන් වන රියදුරන් සාමාන්‍යයෙන් අනතුරු වළක්වා ගන්නේ ඔවුන් මග හැරීමට උත්සාහ කළ ගමනාගමනය නිර්මාණය කරමිනි.",
    "ප්‍රබන්ධයෙන් විවාහ වන චරිත වචනාර්ථයෙන් එකිනෙකා සඳහා නිර්මාණය කරන ලද්දකි.",
    "ළදරුවන් යනු ඕනෑම භාෂාවකින් වැඩසටහන්ගත කළ හැකි පිරිසිදු දෘඩ තැටියකි ",
    "මිනිසාට සෑම රෝගයක්ම සුව කරන ආශ්චර්යමත් ඖෂධයක්  තිබිය හැකිය, එය මීයන් මත ක්‍රියා නොකරන නිසා අපි කිසි විටෙකත් නොදැන සිටින්නෙමු.",
    "රයිනෝස් පරිණාමය වූයේ ආරක්ෂාව සඳහා අං වැඩීම සඳහා ය, නමුත් එය වඳ වී යාමට හේතුව එයයි.",
    "අවුරුදු 25-50ක් තුළ අප සියල්ලන්ම මිය යන නිසා සමහර විට අපට කාල සංචාරකයින් සොයා ගත නොහැක.",
    "නින්ද යනු මරණයේ අත්හදා බැලීමේ අනුවාදය වන අතර, එය ඔබගේ ක්‍රියාකාරකම් මත පදනම් වූ දැන්වීම් සමඟ පවා පැමිණේ.",
    "ස්පයි චිත්‍රපට පිළිබඳ වඩාත්ම යථාර්ථවාදී නොවන දෙය නම් වායු වාතාශ්‍රය පද්ධතිය කෙතරම් පිරිසිදුද යන්නයි!",
    "ක්‍රීඩා වලදී අපි දෘඩ ප්‍රකාර අගුළු ඇරීමට පහසු ක්‍රම හරහා ක්‍රීඩා කරමු. ජීවිතයේ දී අපි පහසු මාතයන් අගුළු ඇරීමට දෘඩ මාතයන් හරහා සෙල්ලම් කරමු.",
    "නිහඬ මිනිසුන් ඝෝෂාකාරී  මිනිසුන්ට වඩා දක්ෂ බව පෙනේ, මන්ද ඔවුන් ඔවුන්ගේ මෝඩ සිතුවිලි තමන්ටම තබා ගනී.",
    "ග්‍රීන්ලන්තය ඇත්ත වශයෙන්ම කොළ පැහැයට හැරේ නම්, අප සියල්ලන්ම ඉස්කුරුප්පු කර ඇත.",
    "ඔබේ සිහිනයේ යමෙක් දක්ෂ දේ පවසන්නේ නම්, එය ඇත්ත වශයෙන්ම ඔබේම දක්ෂතාවය පෙන්නුම් කරයි.",
    "ප්‍රසිද්ධ චිත්‍රපට උපුටා දැක්වීම් බැර වන්නේ නළුවාට මිස ඒවා ලියූ සැබෑ ලේඛකයාට නොවේ.",
    "බයිසිකලයක් පැදවිය යුතු ආකාරය කිසිවෙකු ඔබට උගන්වන්නේ නැත. ඔබ එය ක්‍රියාත්මක කරන තුරු ඔවුන් ඔබව උද්දීපනය කරයි.",
    "මොළය දෙවැන්න නොසලකා හැරියේ මන්දැයි ඔබගෙන්ම විමසන්න.",
    "ඔබගේ මුළු ජීවිතයෙන් 80% ක් පමණ ඔබට අමතක වී ඇති අතර ඔබට මතක ඇති බොහෝ මතකයන් ඇත්ත වශයෙන්ම සිදුවූ දෙයට වඩා නිවැරදි නොවේ.",
    "අනාගතයේදී වීඩියෝ ක්‍රීඩා වලදී ළමයින්ට තම දෙමාපියන්ට එරෙහිව ජයග්‍රහණය කිරීම බොහෝ අපහසු වනු ඇත.",
    "සෑම කෙනෙකුටම අඩුපාඩු තිබේ, ඔබ ඔබේ ඒවා හඳුනා නොගන්නේ නම්, ඔබට නව එකක් තිබේ.",
    "දරුවෙකු ඇති දැඩි කිරීම ඔබේ ආදේශනය පුහුණු කිරීමකි.",
    "ඕපන් ආරම්භ වන්නේ සංවෘත කවයකින් වන අතර, ක්ලෝස් ආරම්භ වන්නේ විවෘත කවයකින් ය.",
    "කිසිම හේතුවක් නොමැතිව ඔබට වෛර කළ, තවමත් එසේ කරන කෙනෙක් සිටී.",
    "පොප්කෝන් සොයාගැනීමෙන් පසු, අහඹු බීජ විශාල ප්‍රමාණයක් පුලුස්සා තිබිය යුතුය.",
    "හොඳ රාත්‍රී නින්දකට වඩා වැදගත් වන්නේ නින්දට යාමයි.",
    "නව මෝස්තර ශිල්පියෙකුට අවශ්‍ය කොණ්ඩා කැපීම නිවැරදිව විස්තර කළ හැකි අය භාග්‍යවන්තයෝ ය.",
    "බොහෝ අය තමන් උපයා නොගත් මුදල් වියදම් කරති, ඔවුන්ට අවශ්‍ය නැති දේවල් මිලට ගැනීමට, ඔවුන් අකමැති පුද්ගලයින් විශ්මයට පත් කිරීමට!",
    "තේමා උද්‍යාන සේවකයින් බිහිසුණු කෑගැසීම් සහ උද්දීපනය අතර වෙනස පැවසීමට හොඳ විය යුතුය.",
    "6 සිට 6:30 දක්වා පැය 5:50 සිට 6:20 දක්වා පැය භාගයක් වැඩියෙන් දැනේ",
    "ලොගවුට් වීමට පෙර අවසන් පිවිසුම් උත්සාහයේදී ඔබගේ මුරපදය නිවැරදිව ලබා ගැනීම අප බොහෝ දෙනා අත්විඳින අවසාන මොහොතේ බෝම්බයක් නිරායුධ කිරීමට ආසන්නතම දෙයයි.",
    "ඇඳට පෙර පොඩ්කාස්ට් වලට සවන් දීම යනු කතන්දර-කාලයේ වැඩිහිටි අනුවාදයයි.",
    "සියලුම අපරාධකරුවන් මංකොල්ලකෑම නැවැත්වුවහොත් ආරක්ෂක කර්මාන්තය වැටෙනු ඇති අතර ඔවුන්ට පහසුවෙන් මංකොල්ලකෑමට යා හැකිය.",
    "තල්මසුන් ටොන් එකක් ඇත්තෙන්ම තල්මසෙකු මෙන් ය.",
    "ඔබ වයසට ගිය විට, ඔබ පරණ ඔබ තාක්‍ෂණිකව නවක වන අතර ඔබේ තරුණ ආත්මය ඔබ මහලු ය.",
    "පැරෂුට් පිළිබඳ බොහෝ සෘණාත්මක සමාලෝචන ඔබට අන්තර්ජාලයේ සොයාගත නොහැක.",
    "මිනිසුන් එය අගය කිරීමට නොසිටින විට අපි ඔවුන්ට වඩාත්ම ආදරය හා අගය පෙන්වමු.",
    "අපි දහස් වාරයක් නිදා ගැනීමට පුරුදු වී සිටිමු, නමුත් එය හොඳින් කළ නොහැක.",
    "පෘථිවිය සුරැකීමට වඩා සතුරු පරිසරයක් සහිත වෙනත් ග්‍රහලෝකයකට යාමට මිනිසුන් වැඩි උනන්දුවක් දක්වයි - ඔවුන් පරිපූර්ණ ලෙස හැඩගස්වා ඇති ග්‍රහලෝකය.",
    "බොහෝ මිනිසුන්ගේ ජීවිතයේ ප්‍රීතිමත්ම අවස්ථාව වන්නේ ඔවුන්ගේ මොළය තවමත් පූර්ණ ලෙස වර්ධනය වී නොමැති අවස්ථාවයි.",
    "වඩාත් ඵලලදායී අනතුරු ඇඟවීමේ ඔරලෝසුව සම්පූර්ණ මුත්‍රාශයකි.",
    "ඔබ බොහෝ විට මිලියන ගණනක් දෙනා සමඟ සමමුහුර්ත කර ඇත.",
    "අපි මුලින්ම සතුන් මත ඖෂධ පරීක්‍ෂා කරන බැවින් මීයන්ගේ ඖෂධ මිනිස් ඖෂධයට වඩා වසර ගණනක් ඉදිරියෙන් සිටිය යුතුය.",
    "නිවාඩු දිනයට පෙර රාත්‍රිය සැබෑ නිවාඩු දිනයට වඩා තෘප්තිමත් ය.",
    "මැදිං ඇඩ් එකක් දාන්න එපැයි 😅 ඔන්න දැම්ම ඈෑ........\n😜Chat Group 👉 @GangOfMafiaTeam \n👨‍💻 @Mafia_Update  ",
    "කොහේ හරි, හොඳම මිතුරන් දෙදෙනෙකු පළමු වරට හමුවෙයි.",
    "අපගේ මොළය එකවරම අපට වෛර කරයි, අපට ආදරය කරයි, අප ගැන සැලකිල්ලක් නොදක්වයි, සහ අපගේ සෑම පියවරක්ම ක්ෂුද්‍ර කළමනාකරණය කරයි.",
    "පිරිමියෙකු වීම උපතේ කාරණයකි. මිනිසෙකු වීම වයස පිළිබඳ කාරණයකි. නමුත් මහත්වරයකු වීම තේරීමකි.",
    "ළමුන් තම ගිණුම් දෙමාපියන්ගෙන් සඟවා තබනවාට වඩා ඉක්මනින් ඔවුන්ගේ සමාජ ගිණුම දරුවන්ගෙන් සඟවනු ඇත.",
    "විකිපීඩියාව යනු අන්තර්ජාලය යනු කුමක්ද යන්නයි.",
    "තේමා උද්‍යානයක් යනු දුරින් කෑගැසීම් ඇසෙන සහ සැලකිලිමත් නොවිය හැකි එකම ස්ථානයයි.",
    "රැහැන් රහිත දුරකථන චාජරයක් රැහැන් රහිත චලනයකට වඩා අඩු නිදහසක් ලබා දෙයි.",
    "ඔබ අකමැති දෙයකට කැමති යැයි ඔබ යමෙකු නැවත නැවතත් විවේචනය කරන්නේ නම්, ඔවුන් එයට කැමති වීම නවත්වන්නේ නැත. ඔවුන් ඔබට කැමති වීම නවත්වයි.",
    "කොහේ හරි ආච්චි කෙනෙක් ඉන්නවා, ඔහුගේ මුනුබුරා ඇත්තටම ලෝකයේ කඩවසම් පිරිමි ළමයා.",
    "කවදා හෝ දවසක මිනිස් දුරකථන හුවමාරුව සැබෑවක් වුවහොත් මිනිසුන් තවමත් වැඩ සඳහා ප්‍රමාද වනු ඇත.",
    "කකුළුවන් ආහාරයට ගත් පළමු මිනිසුන් සන්නාහ සහිත මුහුදු මකුළුවෙකු ආහාරයට ගැනීමට උත්සාහ කළ යුතුය",
    "තනිවම යමක් කිරීම කනගාටුවට කරුණකි, නමුත් එය තනිවම කිරීම සිසිල් ය.",
    "ඔබ යමක් පළ කිරීමෙන් පසු ඔබේ මොළය හදිසියේම සෝදුපත් කියවීමේදී පරිපූර්ණ වේ.",
    "ඔබගේ ධාවන ලැයිස්තුවේ සෑම විටම ඔබ මඟ හැරිය නමුත් ඉවත් නොකරන ගීතයක් තිබේ.",
    "ඊළඟ ශතවර්ෂයේ ළමයින් හොඳ පරිශීලක නාමයන් ගැනීම ගැන අපට වෛර කරනු ඇත.",
    "බුබුලු යනු මිනිසුන්ට වැසි යනු කුමක්දැයි මසුන් ඇල්ලීමයි.",
    "ඔබ වැඩි වැඩියෙන් මුණගැසෙන තරමට, ඔබේ දෙමාපියන් ඔබව හදා වඩා ගත් ආකාරය ඔබ තේරුම් ගෙන අගය කරයි.",
    "කොමාව යනු කෙටි විරාමයකි, කෝමා යනු දිගු විරාමයකි.",
    "කවදා හෝ ඔබ අවදි නොවනු ඇත, නැතහොත් නින්දට නොයනු ඇත.",
    "බර්මියුඩා ත්‍රිකෝණය මෙම සමාකරණයේ පිටවීමේ ද්වාරය විය හැකිය.",
    "අපි වාහන නැවැත්වීමේ ස්ථානයට ඉහළින් සූර්ය පැනල තැබුවහොත් අපගේ මෝටර් රථ උණුසුම් නොවනු ඇති අතර අපට පිරිසිදු ශක්තියක් ලැබෙනු ඇත.",
)
